name: GitHub Release Build

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          ref: ${{ env.GITHUB_REF }}

      - name: Build and upload files to release
        shell: bash {0}
        run: |
          exit_on_error() {
              echo "$1"
              echo "Deleting '$RELEASE_VERSION_NAME' release and '$GITHUB_REF' tag"
              gh release delete --cleanup-tag --yes "$RELEASE_VERSION_NAME"
              git push --delete origin "$GITHUB_REF"
              exit 1
          }

          echo "Setting vars"
          RELEASE_VERSION_NAME="${GITHUB_REF/refs\/tags\//}"
          if ! printf "%s" "${RELEASE_VERSION_NAME/v/}" | grep -qP '^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$'; then
            exit_on_error "The release version '${RELEASE_VERSION_NAME/v/}' is not a valid version as per semantic version '2.0.0' spec in the format 'major.minor.patch(-prerelease)(+buildmetadata)'. https://semver.org/spec/v2.0.0.html."
          fi

          echo "Validating tudo file for '$RELEASE_VERSION_NAME' release"
          if ! test -f "tudo"; then
            files_found="$(ls -a)"
            exit_on_error "Failed to find tudo file. Files found: "$'\n'"$files_found"
          fi

          echo "Generating checksums-sha256.txt file"
          if ! (sha256sum "tudo" > checksums-sha256.txt); then
            exit_on_error "Generate checksums-sha256.txt file failed for '$RELEASE_VERSION_NAME' release."
          fi
          echo "checksums-sha256.txt:"$'\n```\n'"$(cat checksums-sha256.txt)"$'\n```'

          echo "Uploading files to release"
          if ! gh release upload "$RELEASE_VERSION_NAME" \
            "tudo" \
            "checksums-sha256.txt" \
          ; then
            exit_on_error "Upload files to release failed for '$RELEASE_VERSION_NAME' release."
          fi
